server:
    port: 8081
spring:
    devtools:
        livereload:
            enabled: true
    thymeleaf:
        cache: false
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: create-drop
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/vkr
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver
